apiVersion: v1
kind: Service
metadata:
        name: main-server-svc
spec:
        type: NodePort
        selector:
                app: main-server
        ports:
                - targetPort: 5000
                  port: 5000
                  nodePort: 30001

