apiVersion: v1
kind: Service
metadata:
        name: parser-svc
spec:
        type: ClusterIP
        selector:
                app: parser
        ports:
                - port: 8001
                  targetPort: 8001
